### ISSUE TITLE
Generative model

### ISSUE THREAD

**Issue by VuongLong** [sony/sqvae#2]
Thank you for the implementation!

I could not find the code/models for samples generated with a prior learned with PixelCNN. 

Could you kindly share that? Thanks!

**Comment by ytakida** [comment]
Thank you for your interest in our work! and Sorry for the late response.

We're sorry that we are not planning to upload code and models for prior models. We refer to the following repositories for the implementation.
https://github.com/anordertoreclaim/PixelCNN
https://github.com/rosinality/vq-vae-2-pytorch

Since we focused on comparisons among main VAE models (SQ-VAE and other conventional VQ-VAE models) under fair conditions, we used a simple prior model rather than sophisticated ones.
