### ISSUE TITLE
Dequantization step

### ISSUE THREAD

**Issue by SimonKoop** [sony/sqvae#5]
Dear authors,

Thank you for the great paper and the corresponding code!
Could you maybe help me understand where in your code the stochastic dequantization step (E2 in figure 1) takes place? I'm having trouble finding it.

With kind regards,

Simon Koop

**Comment by ytakida** [comment]
Hi SimonKoop,
Thank you for having an interest in our work!

In the practical implementation, we omit the dequantization step, which we found leads to more stable training and better performance. The (conceptual) step is still important because it induces parametric quantization process as its inverse operator.
